<%@include file="header.jsp"%>
  <div class="topbar">
      <div class="fill">
        <div class="container">
          <a class="brand" href="/"></a>
          <ul class="nav">
            <li><a href="/">Home</a></li>
            <li class="active"><a href="/about.html">About</a></li>
            <li><a href="/contact.html">Contact</a></li>
            <sec:authorize access="hasRole('USER_ROLE')"><li><a href="/j_spring_security_logout">Logout</a></sec:authorize>
            <sec:authorize access="hasRole('ROLE_ANONYMOUS')"><li><a href="/login.html">Login</a></sec:authorize>
          </ul>
         
        </div>
      </div>
    </div>

    <div class="container">
     <div class="content">
        <div class="row">
          <div class="span10">
            <h2>About</h2>
            <p>This website was created for RHoK in Berlin on 3rd - 4th december 2011 </p>
            
            <h3>Privacy</h3>
            <p>This website uses Google Analytics, a web analytics service provided by Google, Inc. (&quot;Google&quot;).  
            Google Analytics uses &quot;cookies&quot;, which are text files placed on your computer,
             to help the website analyze how users use the site. The information generated by the cookie
              about your use of the website (including your IP address) will be transmitted to and stored
               by Google on servers in the United States . Google will use this information for the purpose
                of evaluating your use of the website, compiling reports on website activity for website 
                operators and providing other services relating to website activity and internet usage.
                  Google may also transfer this information to third parties where required to do so by law, 
                  or where such third parties process the information on Google's behalf. Google will not associate your IP address with 
                  any other data held by Google.  You may refuse the use of cookies by selecting 
                  the appropriate settings on your browser, however please note that if you 
                  do this you may not be able to use the full functionality of this website. 
                   By using this website, you consent to the processing of data about you by 
                   Google in the manner and for the purposes set out above.</p>
          </div>
          <div class="span4">
          </div>
        </div>
      </div>

      <%@include file="footer.jsp"%>

   </div> <!-- /container -->


<%@include file="end.jsp"%>